# Generated by Django 4.1 on 2022-09-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_choice_votes_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.AddField(
            model_name='vote',
            name='user_id',
            field=models.IntegerField(default=0, verbose_name='user_id'),
        ),
    ]
